// src/lib/types.ts (or wherever you want to keep your types)
export interface Character {
	id?: number; // Optional, as it might be generated by the database
	name: string;
	race: string;
	profession: string;
	// ... other properties
}
