name: avesphere

services:
  app:
    build:
      dockerfile: app.Dockerfile
    ports:
      - '3000:3000'

  db:
    image: postgres:17-alpine
    restart: 'no'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
